Arrival_rates:
  Class 0:
  - 6.0
Number_of_classes: 1
Number_of_nodes: 1
Number_of_servers:
- 2
Queue_capacities:
- 6
Service_rates:
  Class 0:
  - - Exponential
    - 2.0
Simulation_time: 2500
Transition_matrices:
  Class 0:
  - 0.5
