Arrival_rates:
  Class 0:
  - 7.5
  - 12.0
Number_of_classes: 1
Number_of_nodes: 2
Number_of_servers:
- 4
- 2
Queue_capacities:
- 2
- 3
Service_rates:
  Class 0:
  - - Exponential
    - 6.0
  - - Exponential
    - 7.0
Simulation_time: 2500
Transition_matrices:
  Class 0:
  - - 0.0
    - 0.7
  - - 0.6
    - 0.0
