Arrival_rates:
  Class 0:
  - 4.0
  - 5.0
Number_of_classes: 1
Number_of_nodes: 2
Number_of_servers:
- 1
- 1
Queue_capacities:
- 3
- 2
Service_rates:
  Class 0:
  - - Exponential
    - 10.0
  - - Exponential
    - 8.0
Simulation_time: 2500
Transition_matrices:
  Class 0:
  - - 0.675
    - 0.325
  - - 0.15
    - 0.1
